<Project>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <Version>0.2.9</Version>
    <FileVersion>0.2.9.0</FileVersion>
    <AssemblyVersion>0.2.9.0</AssemblyVersion>
    <Authors>Руслан Керусов</Authors>
    <Company>KRS</Company>
    <Product>KRS Эквайринг Монитор</Product>
    <Copyright>Copyright © 2026 Руслан Керусов / KRS</Copyright>
    <NeutralLanguage>ru-RU</NeutralLanguage>
  </PropertyGroup>
</Project>
